# Generated by Django 5.2.6 on 2026-09-07 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('total_links', models.IntegerField(default=0)),
                ('succeeded', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
            ],
        ),
    ]
