# Generated by Django 5.2.6 on 2026-09-07 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('raw_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingestion_run_id', models.UUIDField(db_index=True)),
                ('url', models.URLField(max_length=2048)),
                ('fetch_duration_ms', models.IntegerField()),
                ('fetch_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('chunk_duration_ms', models.IntegerField(null=True)),
                ('chunk_count', models.IntegerField(null=True)),
                ('embed_duration_ms', models.IntegerField(null=True)),
                ('total_duration_ms', models.IntegerField(null=True)),
            ],
        ),
    ]
