# Generated by Django 5.2.6 on 2026-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_document_chunked_content_hash_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='indexed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
